#!/usr/bin/env bash
# Build the Elsevier CAS (cas-sc) manuscript PDF. Requires TeX Live (pdflatex, bibtex)
# and, for the derived inputs, Python. Regenerates the claims-gated tables and the
# verbatim prompts appendix from the single source (claims.json / agent.py), then
# typesets. Figures are regenerated by analysis/make_figures.py (matplotlib).
#
#   bash build.sh
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(cd ../.. && pwd)"

# derived inputs (single source of truth) — tables from claims.json, prompts from agent.py
python3 "$ROOT/analysis/make_tables.py"  --claims "$ROOT/claims.json" --out ./tables >/dev/null
python3 "$ROOT/analysis/make_prompts.py" --out ./appendix_prompts.tex >/dev/null
# figures (skip silently if matplotlib is unavailable)
python3 "$ROOT/analysis/make_figures.py" --claims "$ROOT/claims.json" --out "$ROOT/paper/figures" >/dev/null 2>&1 \
  && cp "$ROOT/paper/figures/Figure_1.pdf" "$ROOT/paper/figures/Figure_2.pdf" ./ 2>/dev/null || true

pdflatex -interaction=nonstopmode manuscript.tex >/dev/null
bibtex manuscript >/dev/null
pdflatex -interaction=nonstopmode manuscript.tex >/dev/null
pdflatex -interaction=nonstopmode manuscript.tex >/dev/null
echo "-> manuscript.pdf"
