#!/usr/bin/env bash
# Build the Elsevier CAS (cas-sc) manuscript PDF. Requires TeX Live (pdflatex, bibtex)
# and, for the derived inputs, Python. Regenerates the claims-gated tables and the
# verbatim prompts appendix from the single source (claims.json / agent.py), then
# typesets. Figures are regenerated by analysis/make_figures.py (matplotlib).
#
#   bash build.sh
set -euo pipefail
# The script lives in paper/tools/ but LaTeX must run where the sources are, so it
# changes into paper/src/. ROOT is the repository root, two levels up from there.
cd "$(dirname "$0")/../src"
ROOT="$(cd ../.. && pwd)"

# Derived inputs (single source of truth). CLAIMS selects which analysis artifact the
# tables and figures are built from:
#   claims.json          - the ORIGINAL five-model confirmatory grid (frozen, hash-cited)
#   claims_revision.json - that same file extended with the two frontier arms (7 models),
#                          produced by analysis/make_revision_claims.py. claims.json is
#                          never mutated; the revision file is a derived superset.
CLAIMS="${CLAIMS:-$ROOT/claims_revision.json}"
[ -f "$CLAIMS" ] || CLAIMS="$ROOT/claims.json"
echo "   claims: $(basename "$CLAIMS")"
python3 "$ROOT/analysis/make_tables.py"  --claims "$CLAIMS" --out ./tables >/dev/null
# Table 0's caption states how the generation intervals compare with the real-firm battery.
# That comparison is COMPUTED here first; the caption reads its artifact, so the count and the
# definition cannot drift from the data the way the hand-asserted "29 of 30" did.
python3 "$ROOT/analysis/synthetic_real_overlap.py" >/dev/null
python3 "$ROOT/analysis/make_firm_table.py" --out ./tables/table0_firm_profiles.tex >/dev/null
# ONE per-model table (Panel A coefficients + Panel B macro decomposition) replaces the
# separate Table 1 and OFAT table, which were keyed on the same unit.
python3 "$ROOT/analysis/make_combined_table.py" --out ./tables/table1_per_model.tex >/dev/null
python3 "$ROOT/analysis/make_prompts.py" --out ./appendix_prompts.tex >/dev/null
# Figure 1 from the original generator; Figure 2 from the revision generator, which is the
# one that carries the half-slope confidence intervals referee 3 asked for and covers all
# seven models. Both skip silently if matplotlib is unavailable.
python3 "$ROOT/analysis/make_figures.py" --claims "$CLAIMS" --out "$ROOT/paper/src/figures" >/dev/null 2>&1 || true
if ! python3 "$ROOT/analysis/make_revision_figures.py" --out "$ROOT/paper/src/figures" >/dev/null 2>&1; then
  echo "   !! WARNING: Figure 2 (with CIs) failed to build -- the figure in the PDF may be stale" >&2
fi
cp "$ROOT/paper/src/figures/Figure_1.pdf" "$ROOT/paper/src/figures/Figure_2.pdf" ./ 2>/dev/null || true

pdflatex -interaction=nonstopmode manuscript.tex >/dev/null
bibtex manuscript >/dev/null
pdflatex -interaction=nonstopmode manuscript.tex >/dev/null
pdflatex -interaction=nonstopmode manuscript.tex >/dev/null
# Every generated deliverable lands in paper/out/. LaTeX must run beside its sources, so the PDF
# is produced in paper/src/ and then moved, and the aux/log/blg litter is cleared instead of
# being left behind -- that litter is what made the old paper/latex/ unreadable.
mkdir -p "$ROOT/paper/out"
mv -f manuscript.pdf "$ROOT/paper/out/manuscript.pdf"
cp -f manuscript.bbl "$ROOT/paper/out/manuscript.bbl" 2>/dev/null || true
rm -f manuscript.aux manuscript.log manuscript.blg manuscript.out manuscript.abs \
      manuscript.fls manuscript.fdb_latexmk
echo "-> paper/out/manuscript.pdf"

# The double-blind manuscript is GENERATED from manuscript.tex and built here, every time. It
# used to be a hand-maintained second copy and it drifted six days behind, so a referee would
# have reviewed the pre-revision paper. Generating it makes that impossible.
python3 "$ROOT/paper/tools/make_anonymous.py" || exit 1
pdflatex -interaction=nonstopmode manuscript_anonymous.tex >/dev/null
bibtex manuscript_anonymous >/dev/null
pdflatex -interaction=nonstopmode manuscript_anonymous.tex >/dev/null
pdflatex -interaction=nonstopmode manuscript_anonymous.tex >/dev/null
mkdir -p "$ROOT/paper/out"
mv -f manuscript_anonymous.pdf "$ROOT/paper/out/manuscript_anonymous.pdf"
cp -f manuscript_anonymous.bbl "$ROOT/paper/out/manuscript_anonymous.bbl" 2>/dev/null || true
rm -f manuscript_anonymous.aux manuscript_anonymous.log manuscript_anonymous.blg \
      manuscript_anonymous.out manuscript_anonymous.abs
# Both manuscripts are built now, so the figure copies they share can go. Deleting them after
# the FIRST build left the anonymous run compiling with draft boxes and failing under set -e.
rm -f Figure_1.pdf Figure_2.pdf
echo "-> paper/out/manuscript_anonymous.pdf"
# A double-blind leak must fail the build, not be noticed at submission time.
python3 "$ROOT/paper/tools/make_anonymous.py" --audit || exit 1
