#!/usr/bin/env python3
"""Build the bibliography a tracked-changes copy needs.

The tracked manuscript cites the current references AND the ones the revision deleted, which
survive inside \\DIFdel markup. Converting it with the current .bib alone leaves those citations
unresolved, so the entries removed since the baseline are restored from the baseline's own
bibliography.

Usage: merge_tracked_bib.py <current.bib> <out.bib> [baseline-ref]
"""
import re
import subprocess
import sys
from pathlib import Path

cur_p, out_p = Path(sys.argv[1]), Path(sys.argv[2])
ref = sys.argv[3] if len(sys.argv) > 3 else "V.1.0"
cur = cur_p.read_text()

old = ""
for path in (f"{ref}:paper/latex/{cur_p.name}", f"{ref}:paper/src/{cur_p.name}",
             f"{ref}:paper/latex/refs.bib", f"{ref}:paper/src/refs.bib"):
    r = subprocess.run(["git", "show", path], capture_output=True, text=True)
    if r.returncode == 0:
        old = r.stdout
        break

key = lambda e: (re.match(r"@\w+\{([^,]+),", e) or [None, None])[1]      # noqa: E731
have = set(re.findall(r"@\w+\{([^,]+),", cur))
add = [e for e in re.split(r"(?=@\w+\{)", old)
       if e.strip().startswith("@") and key(e) and key(e) not in have]

out_p.write_text(
    f"% Generated by merge_tracked_bib.py -- do not edit.\n"
    f"% {cur_p.name} plus the {len(add)} entry/entries removed since {ref}, which the\n"
    f"% tracked-changes copy still cites inside \\DIFdel markup.\n\n"
    + cur + "\n" + "\n".join(add))
print(f"   {out_p.name}: {len(have)} current + {len(add)} restored from {ref}")
